return {
	diagnostics = {
		Error = " ",
		Warn = " ",
		Hint = " ",
		Info = " ",
	},
	git = {
		Added = " ",
		Modified = " ",
		Removed = " ",
		Renamed = " ",
		Untracked = " ",
		Ignored = " ",
		Unstaged = " ",
		Staged = " ",
		Conflict = " ",
	},
	kinds = {
		Array = " ",
		Boolean = " ",
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Copilot = " ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = " ",
		Interface = " ",
		Key = " ",
		Keyword = " ",
		Method = " ",
		Module = " ",
		Namespace = " ",
		Null = "ﳠ ",
		Number = " ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = " ",
		Struct = " ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Value = " ",
		Variable = " ",
	},
	fillchars = {
		foldopen = "",
		foldclose = "",
		fold = " ",
		foldsep = " ",
		diff = "╱",
		eob = " ",
	},
	listchars = {
		space = " ",
		tab = " ",
		trail = "•",
		extends = "❯",
		precedes = "❮",
		nbsp = "␣",
	},
	dap = {
		breakpoint = " ",
		breakpoint_condition = " ",
		log_point = " ",
		stopped = " ",
		breakpoint_rejected = " ",
		pause = " ",
		play = " ",
		step_into = " ",
		step_over = " ",
		step_out = " ",
		step_back = " ",
		run_last = " ",
		terminate = " ",
	},
	misc = {
		collapsed = " ",
		expanded = " ",
		current = " ",
		folder_empty = "",
		folder_closed = "",
		folder_open = "",
		file = "",
	},
}
