# Colors (xcodedark)

[colors.bright]
black = '#7f8c98'
blue = '#6bdfff'
cyan = '#dabaff'
green = '#acf2e4'
magenta = '#ff7ab2'
red = '#ff8170'
white = '#dfdfe0'
yellow = '#ffa14f'

[colors.cursor]
cursor = '#dfdfe0'
text = '#292a30'

[colors.normal]
black = '#414453'
blue = '#4eb0cc'
cyan = '#b281eb'
green = '#78c2b3'
magenta = '#ff7ab2'
red = '#ff8170'
white = '#dfdfe0'
yellow = '#d9c97c'

[colors.primary]
background = '#292a30'
foreground = '#dfdfe0'

[colors.selection]
background = '#414453'
text = '#dfdfe0'

[general]
live_config_reload = true

[window]
blur = true
opacity = 0.94
padding.x = 4
padding.y = 0
option_as_alt = 'Both'
dimensions.columns = 90
dimensions.lines = 25
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "Hack Nerd Font Propo"
bold.family = "Hack Nerd Font Propo"
italic.family = "Hack Nerd Font Propo"
bold_italic.family = "Hack Nerd Font Propo"
size = 12.0

[cursor]
style = "Block"
vi_mode_style = "Block"
unfocused_hollow = true
