name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Install minisign
        run: |
          wget https://github.com/jedisct1/minisign/releases/download/0.12/minisign-0.12-linux.tar.gz
          tar -xf minisign-0.12-linux.tar.gz --directory ${HOME}
          echo "${HOME}/minisign-linux/x86_64/" >> $GITHUB_PATH

      - name: Build and sign
        run: |
          echo "${MINISIGN_SECRET_KEY}" > minisign.key
          zig build -Doptimize=ReleaseFast -Dtarball --summary all
          rm -f minisign.key
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            ./zig-out/**/*.tar.gz
            ./zig-out/**/*.tar.gz.minisig

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: "./zig-out/**/*.tar.gz,./zig-out/**/*.tar.gz.minisig"
