[general]
live_config_reload = true

[terminal.shell]
program = "/usr/local/bin/zsh"

[window]
blur = true
opacity = 0.94
padding.x = 4
padding.y = 0
option_as_alt = 'Both'
dimensions.columns = 90
dimensions.lines = 25
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"
size = 11.0

[cursor]
style = "Block"
vi_mode_style = "Block"
unfocused_hollow =true
