# Set True Color
set -g @plugin 'wfxr/tmux-fzf-url'
set -g default-terminal "xterm-256color"
set -ga terminal-overrides "xterm-256color"
set -g mouse on
set-window-option -g mode-keys vi
bind 'v' copy-mode

# No longer detatch if you kill current session you are on
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g @t-fzf-prompt '  '
bind-key J run-shell "t"

# action key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set-option -g repeat-time 1000
set-option -g focus-events on

# sane scrolling:
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# Easily Navigate horizontally
bind -n M-H previous-window
bind -n M-L next-window

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R


# Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'

 set -g @resurrect-strategy-nvim 'session'
# Keybindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Open Panes in current directory
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind c new-window -c "#{pane_current_path}"


# Reload Settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a
bind C-j display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-session --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t"
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
# Mac Settings
set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# import
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

set-option -g allow-passthrough on

source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

run '~/.tmux/plugins/tpm/tpm'
