set -g default-terminal "xterm-255color"
set -ga terminal-overrides ",xterm-255color:Tc"
# action key
unbind C-b
set-option -g prefix C-a
set-option -g repeat-time 1
set-option -g focus-events on
set -g mouse on

#### Key bindings

set-window-option -g mode-keys vi

#bind t send-key C-t
# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# XC Shortcuts
# expanded to show all splits
bind s choose-tree
# simpler window to show only sessions
bind S choose-session
bind C-t new-session -A -s todo "cd ~/work/todo && nvim -O backlog.md doing.md done.md"
bind-key c-p popup -w 80% -d '#{pane_current_path}' "`ls ~/.local/bin | fzf`"
bind C-n new-session
bind -n M-X kill-pane
bind -n M-W command-prompt "rename-session '%%'"
bind -n M-p previous-window
bind -n M-P switch-client -p
bind -n M-n next-window
bind -n M-N switch-client -n
bind C-c new-window -n "codebase-session-picker" "ta ~/codebase"
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind -n M-j display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_activity},#{session_name}}' |\
    sort -r |\
    sed '/^$/d' |\
    cut -d',' -f2- \|
    fzf --reverse --header jump-to-session --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t"
#### basic settings

set-option -g status-justify "left"
set-window-option -g mode-keys vi
set-option -g status-fg cyan
set-option -g status-bg black
set -g pane-active-border-style fg=colour167,bg=default
set -g window-style fg=colour11,bg=default
set -g window-active-style fg=colour13,bg=default
set-option -g history-limit 24097
set -sg escape-time 11

#### COLOUR

# default statusbar colors
set-option -g status-style bg=colour236,fg=colour136,default

# default window title colors
set-window-option -g window-status-style fg=colour245,bg=colour234,dim

# active window title colors
set-window-option -g window-status-current-style fg=colour167,bg=default,bright

# pane border
set-option -g pane-border-style fg=colour236 #base02
set-option -g pane-active-border-style fg=colour137,bg=colour235

# message text
set-option -g message-style bg=colour236,fg=colour166

# pane number display
set-option -g display-panes-active-colour colour34 #blue
set-option -g display-panes-colour colour167 #orange

# clock
set-window-option -g clock-mode-colour colour65 #green

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# import
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"


source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf
